add file with my name
WhatWasThatt/next_training pull request #2
Opened 2021-12-15 20:27 UTC by Apleon

fine comment

2021-12-15 20:30 UTC, WhatWasThatt requested changes
where is empty line?

2021-12-15 20:32 UTC, WhatWasThatt requested changes
rename your commit as "Your_name/folder"

2021-12-15 21:05 UTC, Apleon reviewed
complete

2021-12-15 21:05 UTC, KarinaKlevzhits approved these changes

2021-12-17 15:53 UTC, WhatWasThatt approved these changes

2021-12-17 16:16 UTC, closed without merging